### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#10]
- [x] Create a login page with the below design, and using the attached Logo

- [x] Rename from App name to MECHR (which stands for Malawi Child Health Electronic Register)
<img width="299" alt="ANC-Login" src="https://user-images.githubusercontent.com/18394882/59084136-b6b89200-8902-11e9-9d64-43aff8a64685.png">

![MalawiEmblem](https://user-images.githubusercontent.com/18394882/59011091-316aaa00-883c-11e9-9ec4-8fabb2cc164c.jpeg)

**Comment by dubdabasoduba** [comment]
@hmakandi this design was changed to use the wcaro login design. Refer here https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/15

**Comment by hmakandi** [comment]
The page is completed. Name was changed to Malawi HIS based on client feedback

![Screenshot_1561562350](https://user-images.githubusercontent.com/18394882/60192669-f0642500-983e-11e9-9592-ee570becccfb.png)
