### ISSUE TITLE
Remove the deceased from the Siblings list

### ISSUE THREAD

**Issue by bennsimon** [OpenSRP/opensrp-client-giz-malawi#135]
Once the deceased child has a sibling, despite the name being removed from the register, the child will appear as active again. For instance, Kelsey King was reported and confirmed deceased and his sibling is Newly Redistribution. When you click on Newly
Distribution's sibling, Kelsey King’s information appears as normal and I can update his
immunization record. I find this confusing to the user. Maybe if it says “Kelsey King Deceased”
on the sibling.

- [ ] Remove the deceased from the Siblings list of the live siblings

**Comment by hmakandi** [comment]
Confirmed. Represented as a greyed out avatar for the deceased child.Not clickable
