### ISSUE TITLE
Edit Image for use by the login page

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#15]
- [ ] Edit Image for use by the login page according to design considerations

![MalawiEmblem](https://user-images.githubusercontent.com/18394882/59618206-62968480-9130-11e9-8806-934323b8de10.jpeg)

**Comment by rowo** [comment]
@dubdabasoduba Here's a transparent svg: https://en.wikipedia.org/wiki/Coat_of_arms_of_Malawi#/media/File:Coat_of_arms_of_Malawi.svg

You can use the login screen from [Reveal](https://github.com/OpenSRP/opensrp-client-reveal/issues/5) or [WCARO](https://github.com/OpenSRP/opensrp-client-chw/issues/79#issuecomment-459504525) for more detail. Please check with those teams.

**Comment by dubdabasoduba** [comment]
@rowo thanks

**Comment by dubdabasoduba** [comment]
@rowo This design is okay just that I am having an issue with the vector generated from this svg. 
Here is the error `string too large to encode using UTF-8 written instead as 'STRING_TOO_LARGE'.`

On the vector itself I have this warnings 
`Very long vector path (1117 characters), which is bad for performance. Considering reducing precision, removing minor details or rasterizing vector. less... (Ctrl+F1) 
Inspection info:Using long vector paths is bad for performance. There are several ways to make the pathData shorter: * Using less precision * Removing some minor details * Using the Android Studio vector conversion tool * Rasterizing the image (converting to PNG)  Issue id: VectorPath`

Attached are the generated vectors 
[ic_malawi_logo.zip](https://github.com/OpenSRP/opensrp-client-giz-malawi/files/3300766/ic_malawi_logo.zip)

**Comment by dubdabasoduba** [comment]
@hmakandi ^

**Comment by rowo** [comment]
![malawi-1024](https://user-images.githubusercontent.com/1584163/59684597-59e19500-91a8-11e9-974c-95bb608a9b75.png)
![malawi-512](https://user-images.githubusercontent.com/1584163/59684598-59e19500-91a8-11e9-9cb2-db1acc0fc32f.png)
![malawi-256](https://user-images.githubusercontent.com/1584163/59684599-59e19500-91a8-11e9-9312-247795ef19be.png)

**Comment by hmakandi** [comment]
Completed
