### ISSUE TITLE
Service Locations Issue

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#177]
- [x] Server drops child location attribute in the client and the event. Investigate the cause and fix
- [x] Check on null location in app and fix
- [x] Site characteristics not to be shown when the location is null on first login
- [x] Show an error when user attempts to login when location is not set.

**Comment by ekigamba** [comment]
Moved my tasks into https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/180

**Comment by bennsimon** [comment]
**1.  Check on null location in app and fix** - Issue was caused by allowed levels attribute, which needs to include the location level of where the user is stationed

**Comment by ekigamba** [comment]
But why was this intermittent? It worked sometimes and some other times it did not work?

**Comment by bennsimon** [comment]
> But why was this intermittent? It worked sometimes and some other times it did not work?
The allowed levels fixes the null location in the Site Xtics page. however the intermittency is deeper issue affecting the whole app

**Comment by bennsimon** [comment]
- https://github.com/OpenSRP/opensrp-client-core/pull/419

- https://github.com/OpenSRP/opensrp-client-child/pull/104

**Comment by bennsimon** [comment]
**Show an error when user attempts to login when location is not set.** location details are fetched after logging in... That error message is covered
![image](https://user-images.githubusercontent.com/12833877/74041636-13f76c80-49d7-11ea-9457-f2b677f8c912.png)

**Comment by hmakandi** [comment]
Fixed.
