### ISSUE TITLE
Malawi HIS App rollout on playstore for Beta Testing

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#189]
**URL to use in app**: https://jembi-preview.smartregister.org/opensrp/ (the PREVIEW OpenSRP)
Note: Load as Beta Release

 **A short description of the app (up to 80 characters):**
Malawi HIS (eRegister) App is an app for digital capture of OPD, Maternal and Child health data with an aim of automating the paper register process.

 Full description of the app (up to 4000 characters)
**Malawi HIS App (eRegister):**
GIZ Malawi, Jembi, HISP-Malawi and Ona have collaborated with Ministry of Health-Malawi in development of a digital eRegister system in a bid to support and strengthen health systems related to Maternal, Newborn and Child Health (MNCH) some health facilities in Malawi.This is achieved by promoting data analysis, interpretation and use through the implementation of an electronic register system,Open Smart Register Platform (OpenSRP). OpenSRP (smartregister.org), is an open source digital health platform for frontline health workers.

- [x]  Hi-res app icon (512x512 pixels)

- [x] Feature graphic for the app(1024x500 pixels)

- [x] 3 screenshots 
<img width="322" alt="Screenshot 2020-01-29 at 19 11 19" src="https://user-images.githubusercontent.com/18394882/73374405-2c76d100-42cb-11ea-9768-cd3561c7f1c5.png">
<img width="317" alt="Screenshot 2020-01-29 at 19 11 00" src="https://user-images.githubusercontent.com/18394882/73374408-2c76d100-42cb-11ea-9e47-adfd9130ce03.png">
<img width="323" alt="Screenshot 2020-01-29 at 19 10 45" src="https://user-images.githubusercontent.com/18394882/73374420-326cb200-42cb-11ea-9ea4-c4a2b7a6c28a.png">

**Comment by rowo** [comment]
@hmakandi Here are some updated screenshots (cropped to remove black border) and the feature graphic, but just to note for the Play store it's customary to take screenshots from the latest app. The content on these screenshots doesn't match the country.

![malawi-his-playstore-feature-graphic](https://user-images.githubusercontent.com/1584163/73593903-be9ef500-44d6-11ea-85d0-cd608bbe0aa1.png)

![me-anc](https://user-images.githubusercontent.com/1584163/73593869-71228800-44d6-11ea-86cf-9bc96936f557.png)
![me-menu](https://user-images.githubusercontent.com/1584163/73593870-71228800-44d6-11ea-9138-2d199794f1ae.png)
![me-all](https://user-images.githubusercontent.com/1584163/73593871-71228800-44d6-11ea-88b7-e66c8f6338f7.png)

**Comment by bennsimon** [comment]
![playstore-icon](https://user-images.githubusercontent.com/12833877/73721155-a5937f80-4734-11ea-9e5d-67e670e20b6c.png)
the Hi-Res app icon 512x512

**Comment by hmakandi** [comment]
This was done and completed.
