### ISSUE TITLE
Growth and Monitoring-Add Height and Weight

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#2]
- [x] Rename the Weight for Height widget to show growth and monitoring as below
<img width="373" alt="Growth_profile_home" src="https://user-images.githubusercontent.com/18394882/58160914-00a94300-7c88-11e9-8bf6-c65edc85c2b8.png">

- [x] On recording the weight and height, the button changes to reflect the recorded weight in kg / height in cm. The weight and height shown should be greater than 0 and if any of them are 0, show the other,if all are greater than 0 show both.

- [x] The record growth button should be made visible again, when the service is due as per the constraints below
The constraints are as below

For Child < 2 years, weight and height are taken every month
- If child < 2 years, Hint For weight: "Weight should be recorded every month" 
- If child < 2 years, Hint For Height: "Height should be recorded every month" 

For Child > 2 years, weight is taken every month and height is recorded every 3 months
- If child > 2 years, Hint For weight: "Weight should be taken every month" 
- If child > 2 years, Hint For height: "Height should be taken every 3 months"  

On click growing and monitoring, the form below should be visible to enter the weight and height. 
Only store values that are greater than 0. On click "Growth recorded earlier" display date to be chosen and auto-save.
Give a numeric keyboard and allow to 2 decimal places

<img width="487" alt="Screen Shot 2019-05-16 at 16 59 50" src="https://user-images.githubusercontent.com/18394882/57864495-a54d0000-7804-11e9-80ec-d544948e7fa8.png">

The view of the growth and monitoring is as below:
<img width="389" alt="Growth and Monitoring_" src="https://user-images.githubusercontent.com/18394882/58407291-206bad00-8074-11e9-9471-475b615027e6.png">

**Comment by dubdabasoduba** [comment]
![device-2019-06-10-145249](https://user-images.githubusercontent.com/4817531/59193805-8cc7cf80-8b8f-11e9-8834-c1f5a82c86af.png)
![device-2019-06-10-145308](https://user-images.githubusercontent.com/4817531/59193807-8f2a2980-8b8f-11e9-8103-6c81d164bbba.png)
![device-2019-06-10-145137](https://user-images.githubusercontent.com/4817531/59193812-93eedd80-8b8f-11e9-8fd9-cbf8937f4486.png)
![device-2019-06-10-144937](https://user-images.githubusercontent.com/4817531/59193824-99e4be80-8b8f-11e9-9266-cfa6bb3177e4.png)

**Comment by rowo** [comment]
Latest update needs changing
![device-2019-06-20-124302](https://user-images.githubusercontent.com/18394882/59850979-25223900-9374-11e9-8f76-4748eb40988c.png)

**Comment by hmakandi** [comment]
An update on this: weight come before height , and the measurements are all small caps
![Screenshot_1561101875](https://user-images.githubusercontent.com/18394882/59906407-5ef54d00-9411-11e9-9c41-a1e9fe91dad8.png)

**Comment by rowo** [comment]
@dubdabasoduba @hmakandi 

How is the edit weight/height triggered? I have some version of the ZEIR app and can't find an Edit button. 

Please review the below updates. There were a few issues I had with how it was implemented:
- there were too many buttons
- the change date button was big and also I'm not sure why it required a button to get to editing the date but not the weight and height.
- the delete record was super prominent 
- "set" and "dismiss" aren't words that are used anywhere else I don't think unless we're moving towards replacing "Cancel" with "Dismiss" everywhere

## Edit form with keyboard open
- Buttons are fixed to bottom of the dialog
- User has to scroll to see the full dialog contents

![Edit-Weight-Height-02](https://user-images.githubusercontent.com/1584163/59940996-3594eb00-942a-11e9-8e26-57154401c80a.png)

## Edit full form
- The field labels are left aligned. 
- The spacing is tightened between field label and data entry.
- The date field is available for editing
- Delete is in it's own section to give it some importance and align it with the other fields.

![Edit-Weight-Height-01](https://user-images.githubusercontent.com/1584163/59940992-34fc5480-942a-11e9-97fc-aeea824b2ae3.png)

**Comment by hmakandi** [comment]
Height changed to not required. Some bugs arise due to this

- [ ] Growth and Monitoring: Does not allow entry of weight only, record does not reflect, i.e. is not saved when height is not provided

**Comment by rowo** [comment]
@hmakandi ^ I have a few questions [above](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/2#issuecomment-504513108) and any thoughts on the new design?

**Comment by hmakandi** [comment]
Height made optional after feedback from client. Weight is mandatory and error pops up incase it is not entered. New designs implemented.
![Screenshot_1562581646](https://user-images.githubusercontent.com/18394882/60803559-2630d400-a184-11e9-88ae-a95e3e2c1000.png)
![Screenshot_1562581734](https://user-images.githubusercontent.com/18394882/60803642-5a0bf980-a184-11e9-810e-596e6f0907da.png)
