### ISSUE TITLE
ANC: Update population characteristics

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#221]
The population characteristics are defined as below:They should be Global characteristics
Where put as NA, it should be updated as False
<img width="797" alt="Screenshot 2020-02-21 at 14 25 41" src="https://user-images.githubusercontent.com/18394882/75030866-1d440700-54b6-11ea-94bc-8362eabb1788.png">

**Comment by bennsimon** [comment]
done

**Comment by hmakandi** [comment]
Confirmed

**Comment by hmakandi** [comment]
Reopening this issue to allow updating of the population characteristics in production environment. @bennsimon

**Comment by hmakandi** [comment]
Closed
