### ISSUE TITLE
Fix ANC countSelect query

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-giz-malawi#237]
The current implementation ignores the `mainCondition`  passed as param in method `org.smartregister.giz.model.AncRegisterFragmentModel#countSelect` as per https://github.com/OpenSRP/opensrp-client-giz-malawi/blob/preview-release-0.2.7-harmonization-test/opensrp-giz-malawi/src/main/java/org/smartregister/giz/model/AncRegisterFragmentModel.java#L11

**Comment by hmakandi** [comment]
Confirmed
