### ISSUE TITLE
QA Bugs and Issues v0.2.13

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#246]
- [x] National ID is alphanumeric characters and 8 digits long

- [x] <img width="839" alt="Screenshot 2020-03-16 at 16 34 15" src="https://user-images.githubusercontent.com/18394882/76763413-1ef6a700-67a4-11ea-9b25-b87650d3e1ed.png">

- [x] On update registration info, the Village values entered during registration did not show
<img width="695" alt="Screenshot 2020-03-16 at 17 17 19" src="https://user-images.githubusercontent.com/18394882/76767224-50727100-67aa-11ea-9e9e-1da437a5164e.png">

- [x] Blood glucose test not picking up today's test date and prompting for entering date
<img width="576" alt="Screenshot 2020-03-16 at 17 45 15" src="https://user-images.githubusercontent.com/18394882/76769803-f5db1400-67ad-11ea-9eab-2e247993956c.png">

**Comment by bennsimon** [comment]
`On update registration info, the Village values entered during registration did not show`  point to note is that the village is saved .... its just that the reverse binding of value with the hierarchy fails
