### ISSUE TITLE
Search Form: Change the IZ ID parameter to MER ID

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#28]
- [ ] Check that search allows the use of allowed filters, i.e, if selected inactive, do not give the search results of active registered babies within the result set. Use Luit to check this behaviour, he is inactive, but if you search active, he appears.
- [x] Change the IZ ID parameter to MER ID
![Screenshot_1561360815](https://user-images.githubusercontent.com/18394882/59999083-bf7ec700-9669-11e9-97dc-893e042545c3.png)

**Comment by dubdabasoduba** [comment]
@hmakandi Let me confirm with marto how this was to work then we can move for to fixing the inactive thing

**Comment by hmakandi** [comment]
Confirmed done. 
![Screenshot_1562581935](https://user-images.githubusercontent.com/18394882/60803872-dc94b900-a184-11e9-9ddc-6c3c10182fca.png)
