### ISSUE TITLE
ANC 0.2.31 Issues and Bugs

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#288]
- [x] Relevance for pelvic pain does and the specify option do not kick in
![Screenshot_1590136272](https://user-images.githubusercontent.com/18394882/82648621-94f21100-9c20-11ea-9ecb-ed18cc17b8d8.png)

- [x] Hep B Doses on selection of done earlier, do not provide the date picker to select the date.
![Screenshot_1590138475](https://user-images.githubusercontent.com/18394882/82651579-016f0f00-9c25-11ea-8435-d52bc4ade2d4.png)

- [x] C&T The Deworming and malaria step misbehaves as shown below
![Screenshot_1590139536](https://user-images.githubusercontent.com/18394882/82653244-97a43480-9c27-11ea-8f28-00a66ba290dc.png)

- [x] Performance issues on S&F Container noted when the Medications step is empty. When not empty, it is fast.

- [x] Performance issues on C&T noted on Deworming and Malaria step. We need to relook at the composition of this step and maybe consider splitting it.

**Comment by cafootitt** [comment]
@hmakandi do you mean there is still slow performance on the S&F and C&T containers? what do you mean by performance is noted?

**Comment by hmakandi** [comment]
Performance issues in the app were fixed. Fixes included in Native Forms:
- Optimized the UI rendering process by introducing background threads
- Optimized the skipping steps feature in ANC
- Fixed issues on the rendering of radio and checkboxes by passing the layout instead of the widget
- For expansion panel and popup dialog we moved the initialization of its widgets to onActivityCreated() listener
- Fixed issues affecting rendering of several widgets e.g repeating groups and multi select list and more
- Fixed duplicate fragment entries to FragmentManager stack
- Fixed logic for getting relevance of the next step
- Cleaned up of redundant methods
- Optimization of calculation of unrequired fields within ANC
