### ISSUE TITLE
Jembi issues(v0.2.34-beta) - ANC Contact

### ISSUE THREAD

**Issue by Mstjamush** [OpenSRP/opensrp-client-giz-malawi#317]
### Performance Issues from the Contact activity
**1. There's a lag when loading the "Current Pregnancy" page questions**
> Steps
- ANC Clients
- Pick a client a start Contact
- Fill in Quick Check questions
- Click on Profile and fill in Demographic Info, then click NEXT
- The questions on "Current Pregnancy" page takes 5-15 secs to load

**2. There's a lag when loading the "Obstretic History" page questions**
> Steps
- ANC Clients
- Pick a client a start Contact
- Fill in Quick Check questions
- Click on Profile and fill in Demographic information, then click NEXT
- Fill in the Current Pregnancy information and click
- The "Obstretic History" page takes 5-15 secs to load

**3. There's a lag when loading the "Physiological Symptoms" page questions**
> Steps
- ANC Clients
- Pick a client a start Contact
- Fill in Quick Check questions
- Fill in Profile questions
- Click on "Symptoms and Follow-up"
- The "Physiological Symptoms" page takes 5-15 secs to load

**4. There's a lag when loading the "Height & Weight" page questions**
> Steps
- ANC Clients
- Pick a client a start Contact
- Fill in Quick Check questions
- Fill in Profile questions
- Fill in "Symptoms and Follow-up" questions
- Click on Physical Exam
- The "Height & Weight" page takes 5-15 secs to load and the responsiveness of the fields is also slow

**5. There's a lag when loading the "Blood pressure" page questions**
> Steps
- ANC Clients
- Pick a client a start Contact
- Fill in Quick Check questions
- Fill in Profile questions
- Fill in "Symptoms and Follow-up" questions
- Click on Physical Exam
- Fill in "Height & Weight" and click NEXT
- The "Blood pressure" page takes 5-15 secs to load and the responsiveness of the fields is also slow

**6. There's a lag when loading the "Maternal Exam" option questions**
> Steps
- ANC Clients
- Pick a client a start Contact
- Fill in Quick Check questions
- Fill in Profile questions
- Fill in "Symptoms and Follow-up" questions
- Click on Physical Exam
- Fill in "Height & Weight" and click NEXT
- Fill in "Blood Pressure" questions and click NEXT
- The "Maternal Exam" lags on pages take 2-30 secs and responding issue when providing input data to the questions

**7. There's a lag when loading the "Counselling and Treatment" option questions -  lags on pages take 10secs - 2mins and responding issue when providing input data to the questions**
> Steps
- ANC Clients
- Pick a client a start Contact
- Fill in Quick Check questions
- Fill in Profile questions
- Fill in "Symptoms and Follow-up" questions
- Fill in Physical Exam questions
- Click on "Tests"

**Comment by hmakandi** [comment]
The record included the time taken by the user to enter the data and thus were not applicable for the system performance measures being sought. Therefore am closing this issue.
