### ISSUE TITLE
All Clients Menu

### ISSUE THREAD

**Issue by hmakandi** [opensrp/opensrp-client-giz-malawi#329]
The Menu on the all clients profile page should allow for registration into the required register as per the following logic:

1. The parameters to be used to filter eligibility for registration into a specific focus group are: 
- the module which the client currently exists
- the age
- the gender
 2. Based on the above params the client's register menu options should be:
if current_module =OPD, AND age <=5 then show Child Registration and OPD Close menu
if current_module =OPD, AND age >10 AND gender is female then show ANC Registration, Maternity Registration and PNC registration menu
ELSE show OPD Close Menu

There should be a dialog form to confirm this action with the text "Are you sure you want to enrol the client to the <Register> register?" with a yes or no option

![Screenshot_1597647988](https://user-images.githubusercontent.com/18394882/90368323-832ed700-e072-11ea-827a-122f09ae89db.png)

3. Due to the challenges in harmonizing the child enrolment as above on account of the parameters needed for the child registration: On the + button for All Clients and OPD menu, include 2 menus as a work around thus:
- Enrol child under 5
- Enrol other client

**Comment by hmakandi** [comment]
@rowo Please check the above proposed menu for All clients register and advise if ok to be implemented.

**Comment by rowo** [comment]
@hmakandi Is this on the All Clients page or a client's profile?

**Comment by hmakandi** [comment]
@rowo 
1. The client's profile
2.The menu is based from the Child's profile menu, so it is not so different as it has precedence. The word "Enrol"  and the dynamism of the menu is also new because it changes based on who has been selected.

**Comment by rowo** [comment]
@hmakandi Ok thanks. 

So this is on any profile page, not just all clients profile, right? 

I think the dynamic menu is also has precedence from WCARO and BA, so no problem there. "Enrol" is okay if that's what they think will work best.

**Comment by hmakandi** [comment]
@rowo Just confirming this is on the All Clients- client profile only.

**Comment by AnnieMungai** [comment]
0.3.2- debug
This was updated.
