### ISSUE TITLE
OPD: Add medications and disease codes

### ISSUE THREAD

**Issue by hmakandi** [opensrp/opensrp-client-giz-malawi#348]
The client has requested to add the below to the OPD lists:

- [ ] Additional Medications as highlighted in [this data dictionary](https://docs.google.com/spreadsheets/d/18yaXl-fYlM2h57OiikMoYohT-8x_iMrloenivy43rhE/edit#gid=934980224) - drugs/medication list row 370-386. 
Nevirapine (NVP), 50mg
Abacavir/Lamivudine (ABC/3TC), 60+30mg
Abacavir/Lamivudine (ABC/3TC), 600+300mg
Lopinavir/Ritonavir(LPV/r ), 40+10mg
Tenofovir Disoproxil Fumarate/Lamivudine/Efavirenz(TDF/3TC /EFV), 300+300+600mg
Tenofovir Disoproxil Fumarate/Lamivudine/Dolutegravir (TDF/3TC /DTG), 300+300+50mg
Dolutegravir (DTG), 50mg
Cotrimoxazole 240mg/5ml, suspension, 100ml
Etravirine
Raltegravir
Darunavir
Omeprazole 20mg
Cotrimoxazole 240mg/5ml, suspension, 100ml
Etravirine
Haloperidol (on data dictionary row -190)
Sodium Vaporate
CPZ
Resperidol
Gentamicin , 80mg/2ml (on data dictionary - row 145)

- [ ] Additional Disease codes - as highlighted on this [data dictionary](https://docs.google.com/spreadsheets/d/18yaXl-fYlM2h57OiikMoYohT-8x_iMrloenivy43rhE/edit#gid=303692027) - disease list sheet row 224-229.
_code,name_
32c,Malaria in Pregnancy confirmed (32c)
32d,Malaria in Pregnancy presumed (32d)
32atf,Malaria treatment failure <5 (32atf)
32btf,Malaria treatment failure >5 (32btf)
50b,Hernia (Bowel) obstruction (50b)
Gastroenteritis

**Comment by AnnieMungai** [comment]
v.3.0.3- preview

Looks great! 1 missed but will create a separate issue + some bugs I noted.
