### ISSUE TITLE
Release 0.1.0 QA bug fixes

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#35]
- [x] Registration data "Whether the child's mother received 2+ doses of Td" should be changed to Protected at birth (PAB) as per the data dictionary.

- [x] Count of children on the navigation bar does not update unless sync is done

- [x] MR2 is due at {dob} + 15 months not at 18 months

- [x] Investigate the case of Dwinty, 4 weeks old, who Deworming did not appear in recurring services

- [x] UI does not refresh on edit of registration data, and growth data

- [x] On edit of growth data, it picks up current date, which is a problem because if you add a height value, it stores a new date as today for height, and leaves the old date for the weight, hence there is no mapping in terms of age. On edit, it should pick up the date as initially done, and leave the user to change it.

**Comment by dubdabasoduba** [comment]
@hmakandi 

> Investigate the case of Dwinty, 4 weeks old, who Deworming did not appear in recurring services 

Requires more investigation so it won't be part for the release today.

**Comment by hmakandi** [comment]
Issues confirmed as fixed. Follow up issue for UI refresh on mother details [here](https://github.com/OpenSRP/opensrp-client-giz-malawi/issues/55)
