### ISSUE TITLE
Update the OPD register view

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#375]
- [x] From the side menu, the user can navigate to the OPD register view by tapping on the OPD module. 
- [x] The OPD module list view shows all of the clients in the facility’s catchment area listed from the one that was seen the latest. 
- [x] On the OPD register view, the client details are displayed including 2 names (first name and surname), age, register they belong to, gender, and location on the left side column. (see the illustration below).
![image](https://user-images.githubusercontent.com/58034047/122722958-09134400-d27b-11eb-8ba5-01e20c9b2cf0.png)
- [x] On the OPD register view, the right side column shows the client status. If the patient/ client thas visited the OPD today, the flag shows **Seen today** in color green. If the patient has not visited the OPD today, there will be no flag shown, their status will show a blank status. 
- [x] The filter button at the top of the page will filter the patients based on whether seen today or not. When selected (active), the filter button will show only patients that have been seen today.
![image](https://user-images.githubusercontent.com/58034047/122723674-e6355f80-d27b-11eb-9d1e-7458e7408e56.png)
- [x] At the top navigation of the page, the search button allows users to search for a client using their unique number or name (functionality is like in any other register in the app). 
- [x] At the top navigation, tapping on the **+** sign launches the option to register a child under 5 or another client. 
- [x] Tapping on any of the clients listed will navigate the user to that client's profile.

**Comment by paulinembabu** [comment]
@AnnieMungai  Since all the forms are Separate, How do we determine if the Patient has been seen today? Do we check if they checked in or what is this Measured upon.

**Comment by AnnieMungai** [comment]
@paulinembabu if any of the forms in the OPD is filled in today, then the status **seen today** should be activated.

**Comment by AnnieMungai** [comment]
v.0.3.0-debug
Looks good.
