### ISSUE TITLE
Implement form edit on the client profile view

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#377]
- [x] Once a user fills a form (as shown on issue #376) and saves it, it appears in the row with a timestamp. 
![image](https://user-images.githubusercontent.com/58034047/122740316-85625300-d28c-11eb-8323-577df5493b45.png)
- [x] The edit button also becomes available. Tapping on the EDIT button launches the form. Users can edit the form and save changes. 
- [x] On the profile, the time the form was last edited is saved and is the timestamp that the user will see. 
- [x] Note! In situations with multiple users, other users can see forms filled out by other users only when forms are saved and synced.
- [x] Note! If 2 users fill a form for the same patient in 2 different instances, both forms will be viewable on the client profile. For example. If patient visits the diagnosis desk at 1pm and user A fills out a form. This is saved as a visit. If the patient then goes to a different service provider who fills another diagnosis form at 7pm, then this visit is also saved. The patient's profile will therefore have 2 visits recorded and 2 forms filled. 
- [x] Note! If however a patient visits the OP diagnosis at 3pm and a form is filled, the profile will show a form was filled at 3pm. If however the same patient visits diagnosis at 5pm and the from that was filled at 3pm is edited and more details added, only that 1 form will be available on the client profile. The timestamp will however show the last edited timestamp, which in this case is 5pm.

**Comment by AnnieMungai** [comment]
v.0.3.0 - debug
Will test this in the next release so as to test all functionalities.

**Comment by AnnieMungai** [comment]
@paulinembabu forms are still crashing when I tap on edit button.

**Comment by paulinembabu** [comment]
@AnnieMungai Let me install the apk i shared and check

**Comment by AnnieMungai** [comment]
v.0.3.3-debug

Looks good.
