### ISSUE TITLE
OPD module scoping

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#379]
- [x] Based on the data dump shared, update the scoping document for the OPD module highlighting the exact fields that will be affected when updating client table. 
- [x] Create a technical issue on Github for the sync and save option.

**Comment by tychus6** [comment]
The scoping document  is found [here](https://docs.google.com/document/d/18R5axZp5jePbNZlSJFnUQJ9cXawZExSMXrTInkr06FI/edit#) while the save and sync issue has been created [here](https://github.com/opensrp/opensrp-client-giz-malawi/issues/387)
