### ISSUE TITLE
Initial sync speed improvement-Update Core modules with latest code

### ISSUE THREAD

**Issue by tychus6** [opensrp/opensrp-client-giz-malawi#383]
To improve the initial sync speed ,the client core modules were updated with fixes that include batch processing  and other fixes.
Therefore, the GIZ malawi App needs to be migrated with these core modules  for the initial sync speed to improve.

**Comment by AnnieMungai** [comment]
@paulinembabu confirm these changes are on v.0.3.2-debug.

**Comment by paulinembabu** [comment]
@AnnieMungai These changes are already merged in the code

**Comment by AnnieMungai** [comment]
Closing this issue now @paulinembabu
