### ISSUE TITLE
Implement  Save & Sync functionality 

### ISSUE THREAD

**Issue by tychus6** [opensrp/opensrp-client-giz-malawi#387]
Implement  Save & Sync as shown on this [scope document doc](https://docs.google.com/document/d/18R5axZp5jePbNZlSJFnUQJ9cXawZExSMXrTInkr06FI/edit) - workflow 5.2
- [ ] Add `Activate Save & Sync `option  setting configuration line on the config file(Gradle/Properties file) . The setting can either be `True` or `false`. The default should be `false`.
- [ ] Add a **Save** functionality that implements the following  algorithm: 
1. Save the form data entries to the respective tables. 
2. Implement a query that checks whether there’s a visit record on that day by that client. The query should filter the opd_visits_table by the `client id` and `created_date`  that is equal to that day.
3. If the query returns results, exit the function. If the query does not return results, insert an entry in the `opd_visit_table`.
- [ ] On the **Save** functionality with sync method that is called once data has been saved, the method implements the following algorithm:
1. Get the configuration setting for _Activate Save & Sync_.  If the setting is `True`, check whether the device has an internet connection. 
2. If the device has an internet connection,  call the existing `Sync `function. If the device does not have an internet connection, exit the function.   
3. If the setting is` false`, exit the function

**Comment by tychus6** [comment]
Implement  Sync & save as follows
- [ ] Add ‘Activate Save & sync option’  setting configuration line on the config file(Gradle/Properties file) . The setting can either be ' True’ or ‘false’ ,the default should be ‘false’.

- [ ] Add a ‘Save’ functionality that implements the following  algorithm,

1. Save the form data entries to the respective tables
2. Implement a query that checks whether there’s a visit record on that day by that client. The query should filter the opd_visits_table by the 'client id' and ‘created_date’  that is equal to that day.

 
-  If the query returns results, exit the function.

-  If the query does not return results, insert an entry in the opd_visit_table .

- [ ] On the ‘Save’ functionality with a sync  method that is called once data has been saved , the method implements the following algorithm,

1. Get the configuration setting for ‘Activate Save & sync’    

- If the setting is ‘True’, check whether the device has  internet connection
        

1. If the device has internet connection,  call the  existing ‘Sync’ function that syncs data.
2.  If the device does not have internet connection , exit the function.   

- If the setting is ‘false’, exit the function

**Comment by AnnieMungai** [comment]
v.0.3.1-debug
Looks good.

**Comment by AnnieMungai** [comment]
v.0.3.7-preview
Looking good now.
