### ISSUE TITLE
Create 'pharmacy' table

### ISSUE THREAD

**Issue by tychus6** [opensrp/opensrp-client-giz-malawi#388]
Create 'opd_pharmacy' table on the App with the following table structure in line with the [scoping doc](https://docs.google.com/document/d/18R5axZp5jePbNZlSJFnUQJ9cXawZExSMXrTInkr06FI/edit),  workflow 5.9

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-e0a37834-7fff-79fa-283e-5182f15cec1c"><div dir="ltr" style="margin-left:0pt;" align="left">

Column name | datatype | Required
-- | -- | --
prescription | Text |  Yes
medicine_available | Boolean(YES/NO) | Yes
alt_medicine | Boolean(YES/NO) | No
medicine_refer | Text | No
medicine_dispensed | Varchar | No
dosage | Text | No
frequency | Integer | No
duration | Integer | No
special_instrunctions | Text | No
referral_medicine | Boolean(YES/NO) | No
referral_location_med | Varchar | No

</div></b>
</body>
</html>

**Comment by AnnieMungai** [comment]
@tychus6 this table should already be existing as it was something that was in the previous flow. @paulinembabu kindly confirm.

**Comment by tychus6** [comment]
Closing this issue since we will only need two tables namely; [opd_visit_details ](https://github.com/opensrp/opensrp-client-giz-malawi/issues/395)and [opd_client_visits](https://github.com/opensrp/opensrp-client-giz-malawi/issues/394)
