### ISSUE TITLE
Create 'danger_signs' table

### ISSUE THREAD

**Issue by tychus6** [opensrp/opensrp-client-giz-malawi#389]
Create 'opd_danger_signs’  table on the App with the following table structure in line with the [scoping doc](https://docs.google.com/document/d/18R5axZp5jePbNZlSJFnUQJ9cXawZExSMXrTInkr06FI/edit#),  workflow 5.6

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-157354ee-7fff-77c7-eff7-9b46f9124157"><div dir="ltr" style="margin-left:0pt;" align="left">

Column name | Data type | Required
-- | -- | --
opd_danger_signs | Varchar | Yes
opd_danger_signs_proceed | Varchar | Yes
opd_danger_signs_treat | Boolean(YES/NO) | Yes
opd_vital_signs | Boolean(YES/NO) | Yes
body_temp | Varchar | No
pulse_rate | Varchar | No
current_weight | Varchar | No
height | Varchar | No
opd_bp_note | Varchar | No
bp_systolic | Integer | No
bp_diastolic | Integer | No
oximetry | Integer | No
respiratory_rate_note | Varchar | No
respiratory_rate | Integer | No
convulsions_history | Boolean(YES/NO) | Yes
opd_health_concerns | Varchar | Yes
specific_complaint_other | Varchar | Yes

</div></b>
</body>
</html>

**Comment by AnnieMungai** [comment]
@tychus6 where is this table being created. Not server side I hope? Coz we agreed that we are not changing that.

**Comment by tychus6** [comment]
Closing this issue since we will only need two tables namely; [opd_visit_details ](https://github.com/opensrp/opensrp-client-giz-malawi/issues/395)and [opd_client_visits](https://github.com/opensrp/opensrp-client-giz-malawi/issues/394)
