### ISSUE TITLE
Recheck the Data Dictionaries

### ISSUE THREAD

**Issue by dubdabasoduba** [OpenSRP/opensrp-client-giz-malawi#39]
- [x] Make sure all required fields are marked as required - https://github.com/OpenSRP/opensrp-client-giz-malawi/pull/38#discussion_r305805747

- [x] Reword some long questions to make them more readable for a UX point of view - https://github.com/OpenSRP/opensrp-client-giz-malawi/pull/38#discussion_r305804803

**Comment by hmakandi** [comment]
Rechecked and some changes done to the text
