### ISSUE TITLE
Populate values for inter-dependant forms

### ISSUE THREAD

**Issue by hamza-vd** [opensrp/opensrp-client-giz-malawi#399]
Implement the functionality to pre-populate fields or apply relevances to fields in a form, based on values from the other form. 
- [x] Between forms. 
- [x] On the history page

**Comment by AnnieMungai** [comment]
Need a 2nd device to fully test this.

**Comment by AnnieMungai** [comment]
v.0.3.3.
Looks good, if additional issues arise, will create separate issues.
