### ISSUE TITLE
App allows entry of future date as the Last menstrual period date

### ISSUE THREAD

**Issue by tychus6** [opensrp/opensrp-client-giz-malawi#404]
On the diagnosis form, the App currently allows entry of future dates as the last menstrual period date
![20210714_042219](https://user-images.githubusercontent.com/7522357/125630672-0d9a25dd-039b-4a75-aee3-62fec0a6c890.png)

Expected behavior
The app should not allow entry of dates beyond today as the last menstrual date

**Comment by AnnieMungai** [comment]
@tychus6 when you try to save the form, does it allow you to save record?

**Comment by AnnieMungai** [comment]
v.0.3.2-debug

Looks great!
