### ISSUE TITLE
Amend the labels on the diagnosis form

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#406]
- [ ] Add section header to read **Preliminary diagnosis** - for the preliminary diagnosis (row42 on the [data dictionary ](https://docs.google.com/spreadsheets/d/18yaXl-fYlM2h57OiikMoYohT-8x_iMrloenivy43rhE/edit#gid=1957865784)- highlighted in green) 
- [ ] Add section header to read **Final diagnosis** for the [final diagnosis](https://docs.google.com/spreadsheets/d/18yaXl-fYlM2h57OiikMoYohT-8x_iMrloenivy43rhE/edit#gid=1957865784) (row 76 - highlighted in green). 
![image](https://user-images.githubusercontent.com/58034047/125943191-3645c1b0-eb37-43fd-8c9e-45264d3663b5.png)

**Comment by AnnieMungai** [comment]
@hamza-vd this was not done.

**Comment by hamza-vd** [comment]
@AnnieMungai 
This is done, will be available in the next release.

**Comment by AnnieMungai** [comment]
v.0.3.4-debug
Looks good!
