### ISSUE TITLE
Implement reporting for the OPD module

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#408]
- [ ] Create HIA2 reports for the OPD module. To navigate to the OPD report, tap on the reports >> DHIS2 reports >> OPD
- [ ] On the OPD reports,  split the report into the following segments/subheadings:
- OPD summary 
- Malaria indicators
- TB indicators
- [ ] Implement different indicators using the data dictionary highlighted [here](https://docs.google.com/spreadsheets/d/1dwKySCdvPKPAgAKgU3Np-r5tjXKG6i7FYxIWtfMJr9M/edit#gid=1001715146). 
Note! The daily tallies are read-only while the draft reports are editable. The reporting functionalities work like any other report in the application.

**Comment by paulinembabu** [comment]
@AnnieMungai Which Indicators go to the OPD Summary Section?
Also the TB indicators Tab only shows the Labels, Is this also being Implemented?

**Comment by paulinembabu** [comment]
On this issue, For the Diagnosis Counts, If the user records the Final Diagnosis, this is what will be used to on the Indicator Counts. If the Final Diagnosis is Blank then we use the Preliminary Diagnosis Record on the Indicator Counts.
This is to avoid Double counts when the user has submitted both the Preliminary Diagnosis and the Final Diagnosis

**Comment by paulinembabu** [comment]
@AnnieMungai Kindly Add the Indicator Codes for Row 8 through to Row 12 in the data Dictionary

**Comment by AnnieMungai** [comment]
v.0.3.6.- debug

Some indicators that have complete requirements are missing.
