### ISSUE TITLE
Diagnosis form: HIV diagnosis date unknown option showing even if the date is provided

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#411]
- [ ] The HIV diagnosis date unknown option is showing on the diagnosis form even when the diagnosis date has been provided.  The option should be hidden if the user adds a date diagnosed as HIV positive. If not diagnosis date has been provided, then the option 'diagnosis date unknown' should be available.
https://user-images.githubusercontent.com/58034047/126491359-48e5db53-3077-4cfc-9c29-5e7134190d4c.mp4

**Comment by hamza-vd** [comment]
@AnnieMungai 
In case if the HIV status is negative and the diagnosis date is also provided, then the option 'diagnosis date unknown' should be visible or hidden?

**Comment by AnnieMungai** [comment]
@hamza-vd as long as the date is provided, the diagnosis date unknown should be hidden. If there is no date provided then the diagnosis date unknown option becomes available for the user to select.

**Comment by AnnieMungai** [comment]
v.0.3.5-debug

Looks great!
