### ISSUE TITLE
HIV status, once client has been diagnosed as HIV positive - to be not editable

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#412]
- [ ] On the diagnosis form, HIV status, once a client has been diagnosed as HIV positive - to be not editable. This means that once a user is diagnosed as HIV positive, then in subsequent visits to the OPD the status is not editable.
Questions that come up
1. What happens if this diagnosis was a false positive? 
2. Does this add complexity to the diagnosis form? What is the LOE for this? Is this implemented for any other module in the app? ANC? PNC? If it exists, how do we implement it? 
3. Can we actually collect this information elsewhere and not on the diagnosis form? Example for the child register, the information is captured during registration and this is displayed on the child profile as part of child details.

**Comment by tychus6** [comment]
@AnnieMungai  from our preliminary discussions it seemed the option of capturing this information on the registration form would still not address the issue of false positives. I am thinking that on the diagnosis form we can pull the results of the last diagnosis. if the results was positive, we make the field uneditable but there should an option that explicitly allows the results to be turned back for false positives. If the results was negative we make the field editable.

**Comment by AnnieMungai** [comment]
@tychus6 thanks for this. Are we able to scope this out a bit for the engineers? Possibly using the fields on the data dictionary? Approx LOE could also be quite helpful.

**Comment by tychus6** [comment]
@AnnieMungai  i have documented the proposed approaches [here](https://docs.google.com/document/d/1bLng7caaCRKndtqPtpGoXLpZsbsxMi7y/edit#)

**Comment by AnnieMungai** [comment]
Implementation is [here](https://github.com/opensrp/opensrp-client-giz-malawi/issues/437)
