### ISSUE TITLE
Sync issue across different users in the OPD

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#413]
v.0.3.3-debug
- [ ] Initial sync not able to complete on a new install. 
![image](https://user-images.githubusercontent.com/58034047/126991346-b27756ed-55a0-4c00-8251-246c6e7066e7.png)
- [ ] Save and sync button taking a long time to respond. A client entered on one device is taking over 20min to show on another device. This should take about 1minute or less.

**Comment by paulinembabu** [comment]
@AnnieMungai 
1. For issue one, you have to give the Device sometime to finish the Sync. 
2. For issue two,  I have tried to manually trigger Sync After Saving an event and was able to see the details on the other device in under a one minute. Took like 10 seconds or Less. 
Have tried this Severally and it seems to be working. 

NB:Make sure that initial sync is Complete for both Devices

**Comment by AnnieMungai** [comment]
v.0.3.4
@paulinembabu I am still facing the same issue on sync. It seems to get stuck at some point in the sync. So it is not completing the initial sync which I am thinking is the same issue that is happening in production. When the initial sync gets stuck, any other sync in the device will get stuck.
