### ISSUE TITLE
Add a sync button on OPD forms

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#416]
- [ ] Add a sync button on the forms for each client. This will ensure that the user can quickly sync data for any of the forms to see data entered by another user without having to use the main register sync function on the side panel. The Save button remains the same and when a user is connected to the internet, save invokes sync too. This functionality however applies to users who are entering data on a form but not those downloading data entered on another form (for forms that are linked: Diagnosis, Treatment, Lab and pharmacy).

**Comment by rowo** [comment]
@AnnieMungai Just to get a better understanding: is the expectation here that we have an almost "live" form like Google Docs where if two separate users are editing the same form on two different devices, they can coordinate edits to that specific form with each other without submitting it? Or would edits only appear if the form was completed and saved? How would edits work if two entries conflict? Is there a reason this has to be on the form itself and not on the profile?

**Comment by AnnieMungai** [comment]
@rowo 
- The issue was raised for forms that are linked to each other. Like the diagnosis and Lab form. 
- It is not necessarily 2 people editing the same form but it is a user who needs to see data that was entered by another person on different forms. 
- No, this does not have to be on the forms themselves. It could be on the client profile or anywhere else that we could activate manual sync. The users want to not have to navigate to the side panel to do a manual sync when they are already in the OPD register and going on with work. No tracking of forms.

**Comment by rowo** [comment]
Conclusion: 
- Button at top of profile next to pulldown
- Toaster message when synced with time.

**Comment by rowo** [comment]
@HenryRae for next steps on this I messaged you and Anne. Let me know if you have questions

**Comment by HenryRae** [comment]
if we are syncing all the data in the app and not just for a specific user, this might not be the most appropriate place to place the sync option. we can have a general sync some where in the Hamberg menu(if any)/home screen or have an auto sync option in settings that can be managed to sync maybe every after n-minutes.

Is it also possible to have an auto background sync too?

cc: @rowo @AnnieMungai @paulinembabu

**Comment by HenryRae** [comment]
Here's [link](https://www.figma.com/file/6OmG5NmTC0qIexQPea1SPm/Emmunize-July-2021?node-id=16%3A301) to the design files

Documentation:

1. When user clicks on the sync button, we show a "sync started" toast
 <img width="138" alt="Screenshot 2021-07-28 at 16 56 27" src="https://user-images.githubusercontent.com/31955469/127334862-03eac6eb-0eb7-4155-b87a-5cc2585c94a5.png">
 
 which after a few seconds changes(text changes) to "Syncing".
<img width="98" alt="Screenshot 2021-07-28 at 16 57 40" src="https://user-images.githubusercontent.com/31955469/127335076-448cccbf-ef35-4ddc-b190-a05ce9eb4671.png">

2. When the sync is complete we show the sync complete toast. 
<img width="90" alt="Screenshot 2021-07-28 at 16 58 27" src="https://user-images.githubusercontent.com/31955469/127335234-4c2dab12-9dc3-401a-a231-9dc651d8cc81.png">

3. When the sync fails, we inform the user using sync failed toast
<img width="86" alt="Screenshot 2021-07-28 at 16 59 22" src="https://user-images.githubusercontent.com/31955469/127335387-3ba9c0fd-7771-4e83-807b-65f57ca0ad03.png">

4. When the user clicks sync when there's a sync that's already in progress, we inform them that there's a sync already in progress
<img width="135" alt="Screenshot 2021-07-28 at 17 00 53" src="https://user-images.githubusercontent.com/31955469/127335641-936b9f34-60a1-45e0-8b59-e2d048da7984.png">


**Note:** We are not able to check for the cause of sync failure. We also don’t check for internet connection before sync starts.

**Comment by AnnieMungai** [comment]
@HenryRae looks good!
