### ISSUE TITLE
Perform load testing on Malawi HIS Prod  app

### ISSUE THREAD

**Issue by tychus6** [opensrp/opensrp-client-giz-malawi#417]
Perform Load testing on Malawi production app.

Additional details:
Test to be performed on the following endpoints
{{url}}/opensrp/rest/event/sync?serverVersion=0&providerId={{providerid}} &limit=250
{{url}}/opensrp/rest/settings/sync?serverVersion=0

Access credentials :
To be provided during actual testing

Indicators to monitor are:
- [ ] Average response time
- [ ] Failure/error rate
- [ ] Number of users generating the load at a given time
- [ ] Transaction count/load generated within the specified time during which the test was running

Support engineer 
Pauline

**Comment by tychus6** [comment]
The results of the load test were as follows;

**Load tests summary**
GetWithLimit set to 250
Optimal number of users = 4
Highest processed requests per second = 2.0/s
Test Duration: 3 minutes, 6 seconds
Transactions Count: 60
Average Response Time: 12265 ms
Median Response Time: 11841 ms
90% Response Time: 12557 ms
Min Response Time: 9812 ms
Max Response Time: 19652 ms
Sync(with no limit)
Optimal number of users = 13
Highest processed requests per second = 4.9/s
Test Duration: 3 minutes, 7 seconds
Transactions Count: 170
Average Response Time: 14052 ms
Median Response Time: 13694 ms
90% Response Time: 15990 ms
Min Response Time: 7993 ms
Max Response Time: 31694 ms

A detailed report is attached below;
[RefinedResults.zip](https://github.com/opensrp/opensrp-client-giz-malawi/files/6943977/RefinedResults.zip)

**Comment by AnnieMungai** [comment]
**Additional notes**
This was mainly a GET test (server to client). 
How to work on this:
1. Work to optimize  the server 
2. Check the server configurations
**Areas to focus on:** 
a. Increasing the number of users that use the server without any problems (currently it is 4 only!!!)
b. Reducing the response time. 
c. Enhance TPS (with the fixes on a and b this can automatically change).

**Comment by tychus6** [comment]
After a further review of the load test results,  the findings were as follows;
1. The SSL exemption error that was encountered when making the `GET` request with more than 4 users was a result of misconfiguration on the Jmeter tool used to conduct the test. To fix the issue, the configurations need to be updated.
2. It was hard to determine what was causing the memory hog since the SSL error was present. We should be able to investigate what might be causing the memory hog once the SSL error has been resolved.
Next steps:
Re-do the Load test

**Comment by tychus6** [comment]
The results from the second round of the test were as follows:
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-e49e14a8-7fff-01e5-c75f-1bb3fa5f97fd"><div dir="ltr" style="margin-left:-5.4pt;" align="left">

The optimal number of users | 10 | 60
-- | -- | --
Test Duration | 3 minutes, 17 seconds | 6 minutes, 42 seconds
Transactions Count | 66 | 88
Average Response Time | 29068ms | 177902ms
Median Response Time | 27217ms | 161193ms
90% Response Time | 33429ms | 285504ms
Min Response Time | 20871ms. | 52084ms
Max Response Time | 73277ms. | 401833ms

</div></b>
</body>
</html>
Findings

-The Server internet speed is extremely low approx. 0.92 mb/s:

Speedtest by Ookla     
Server: Telekom Networks Malawi - Blantyre (id = 7038)
ISP: TNM
Latency:     0.85 ms   (0.09 ms jitter)
Download:     0.92 Mbps (data used: 644.5 kB)
Upload:     0.92 Mbps (data used: 1.7 MB)
Packet Loss:     0.0%

-It takes an average of 2 minutes to establish a server connection.
-The Server can optimally support 60 concurrent users.
-The server is not closing all connections (it’s hanging) for more than 30 threads, the connections had to be manually killed.

Recommendation.
-Need  to increase the Server internet speed from 0.9 mb/s to at least  100 mb/s
-Need to re-do the test once the internet speed had been increased

Detailed [report](https://docs.google.com/document/d/1b1Kom4lOZzB4FpUxZ7sB0_nv1YahP2gE/edit#)

**Comment by AnnieMungai** [comment]
Completed and report shared.
