### ISSUE TITLE
Medication and disease codes - amendments

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#427]
- [x] Add:  Gentamicin , 80mg/2ml (on data dictionary - row 175)
- [x] Remove one: Chlorpromazine - 100mg listed 
![image](https://user-images.githubusercontent.com/58034047/128342628-501332bc-2c5f-4439-b2ad-f27a080954c5.png)
- [ ] Disease codes - not clear which is for under 5 or over 5. Amend the signs for this to be clear for Malawi treatment failure. 
![image](https://user-images.githubusercontent.com/58034047/128342816-367d2c54-d7b0-400b-aa03-e0ea0ffc95fd.png)

Follow up to issue #348

**Comment by paulinembabu** [comment]
@AnnieMungai For the Disease Code the JSON that is being submitted has the correct Symbols, the API sending the data to the server is the one that seems to have an issue with Conversion. 
This will need to be a separate issue to fix the API.

**Comment by AnnieMungai** [comment]
@paulinembabu kindly create the issue for the server API issue.

**Comment by AnnieMungai** [comment]
@paulinembabu cannot test this due to issue #430 

Fis required ugently.

**Comment by AnnieMungai** [comment]
v.0.3.2
Lgtm - there is however need to look at the sync functionality so it shows sync complete when everything has completed loading!
