### ISSUE TITLE
Implement HIV status capture functionality

### ISSUE THREAD

**Issue by tychus6** [opensrp/opensrp-client-giz-malawi#437]
Implemented functionality that allows a user to capture a client's HIV status only once, and update the status in the event of false-positive HIV results.
**Requirements**
1. The application should have the ability to capture the client’s HIV status and once this information has been captured, the application should not require the user to submit this piece of information during subsequent visits. 
2. The application should have a means of updating false-positive HIV results. 

**Workflow**

1. Once a user has navigated to the diagnosis page, the client’s HIV results for the previous visit will be retrieved.

- If the result was positive, the field will be editable allowing the user to update the results.  This will provide the user with an option of updating the results in case the previous result was a false positive.

- If the result was negative, the user will still be able to update the results

2. If the client does not have a previous visit, the user can update the HIV status of the client at that instance

**Development**

- [ ] Add a must fill requirement on HIV status  field

- [x] Implement a query that retrieves the client’s HIV status based on the last OPD visit and should implement the following logic.

1. Select all opd_visits, filter by the client ID, sort by visit date, and limit the results to 1 so that the last visit is selected.
2. From the query results, pull the HIV status from the diagnosis record.

- [ ] Implement save functionality that will save HIV status alongside other details captured on the diagnosis page.

**Comment by AnnieMungai** [comment]
v.0.3.5-preview
Looks good!
