### ISSUE TITLE
Sync not happening between 2 devices

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#449]
V.0.3.4-preview (26th Aug release)
users: happykid2 and happykid3
- [ ] There seems to be a lag with sync between 2 users. I have not been able to sync data from tablet A to tablet B for over 30hrs. 
- [ ] The save and sync button seems not to have the sync functionality.
- [ ] Manual sync on the client profile seems to also not work properly.
![image](https://user-images.githubusercontent.com/58034047/130986721-14b66c4c-141d-4f4f-aae0-8ede689cc810.png)
![image](https://user-images.githubusercontent.com/58034047/130986285-ef883897-109b-4c20-8825-a6ffd655a358.png)

**Comment by paulinembabu** [comment]
Issue is Closed. New issues are created
