### ISSUE TITLE
OPD 2 indicators pulling zero data

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#460]
- [ ] 2 indicators highlighted in pink on [data dictionary](https://docs.google.com/spreadsheets/d/1dwKySCdvPKPAgAKgU3Np-r5tjXKG6i7FYxIWtfMJr9M/edit#gid=1001715146) and showing 0 figures even though data was entered. 

![image](https://user-images.githubusercontent.com/58034047/137955900-312291d0-bb58-40b4-97ee-482fff2c92be.png)

**Comment by hamza-vd** [comment]
@AnnieMungai 
Can you mention the daily tally date and user for which this is happening?

**Comment by AnnieMungai** [comment]
kaipa - preview apk (v.0.3.1-beta)
20th October
