### ISSUE TITLE
Lab form logic amendment

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#467]
The clinician will order lab tests and Radiology examinations required on the preliminary diagnosis form. 
- [x] The lab form should repopulate with the data entered on the diagnosis form for the tests ordered- if data has been synced on both devices - leave this at the top of the page. 
- [x] On the lab form, if the lab technician confirms that with a yes, that tests ordered were conducted, then the Add tests conducted pops out and they can select the tests that were conducted.
- [x] If the lab technician confirms that some of the tests were done. The Add tests were conducted and Add tests not conducted pop-ups. They can then fill the test and test results of the tests conducted. They can also fill the tests that were not conducted. With each test, the form to fill reason why test was not conducted is filled in. Note!! Each individual test not conducted should allow users to fill individual reasons why it was not conducted.
- [x] If none of the tests were conducted, the tests Add tests not conducted should pop up and user can select from a list the test not conducted.  They can also fill the tests that were not conducted. With each test, the form to fill reason why test was not conducted is filled in. Note!! Each individual test not conducted should allow users to fill individual reasons why it was not conducted.
Question - Can we make the colour of the tests not conducted pop up a different colour- red maybe to make it different from the blue colour of tests conducted?

Note! This is the [amended data dictionary](https://docs.google.com/spreadsheets/d/18yaXl-fYlM2h57OiikMoYohT-8x_iMrloenivy43rhE/edit#gid=1875532984) - Lab form- areas marked on gray changed.

**Comment by roywanyaga** [comment]
@AnnieMungai 
Please update the data-dictionary for the issue

**Comment by AnnieMungai** [comment]
@hamza-vd @roywanyaga issue and data dictionary updated. We can have a chat on implementation if it is not clear.

**Comment by AnnieMungai** [comment]
V.0.4.2-preview
Looks good!
