### ISSUE TITLE
Change the error message when logged out

### ISSUE THREAD

**Issue by AnnieMungai** [opensrp/opensrp-client-giz-malawi#473]
When  ALL caps is used for user name, it logs one in  and a few seconds later one is kicked out from the system with a message that my account has been disabled. The transaction has so far not been allowed with the wrong username. Using the right user name being able to log in again.

Consider changing the error message that comes -Instead of 'Your account has been disabled/deleted' --display a different message '**_Please log in with the correct user name and Password_**'.

**Comment by roywanyaga** [comment]
Tagging @dubdabasoduba  to this issue

**Comment by roywanyaga** [comment]
Solution is to update opensrp-client-core to latest version. Comprehensive regression testing would be needed to ensure the update does not affect any existing functionality.

**Comment by AnnieMungai** [comment]
@roywanyaga will this need to apply to both preview and prod instances?

**Comment by roywanyaga** [comment]
@AnnieMungai yes. but after we've tested.

**Comment by AnnieMungai** [comment]
V.0.4.2-preview
Looks good!
