### ISSUE TITLE
Scan QR code opens on edit of MER ID number

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#50]
Steps: Go to Add patient, Click on MER ID. Currently it goes to SCAN QR Code.

- [x] Make the field editable, because Malawi does not have QR codes in scope

- [x] Disable the Scan QR code button

**Comment by ekigamba** [comment]
1 day

**Comment by hmakandi** [comment]
Confirmed as disabled
