### ISSUE TITLE
Child register page record growth button

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#51]
Steps: Login and go to the child register. On the child register page, there is a button for record weight. Currently, this button has no action.

- [x] On click of the "record growth" button on this register, it should open the Record growth form as below. It is the same action as "Record growth" button within the vaccination card.
![Screenshot_1566289862](https://user-images.githubusercontent.com/18394882/63331314-1b01c400-c33e-11e9-88de-7e7f478aeeb1.png)

**Comment by ekigamba** [comment]
1 day

**Comment by hmakandi** [comment]
Confirmed.QA Passed
