### ISSUE TITLE
Child profile edit recurring services

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#52]
Steps: Go the child's vaccination view for a child above 6 months, and administer a recurring (Vitamin A and/or deworming), click on the kebab menu which takes you to the profile view, click on the kebab menu and click edit recurring services

- [x] The edit of Vitamin A shows for all possible Vitamin A scheduled items and allows for edit for all the schedules even those that have not been administered. Ensure only the one that has been administered shows in green, the others should show as due on the respective calculated due dates.
![Screenshot_1566295300](https://user-images.githubusercontent.com/18394882/63337999-ada86000-c34a-11e9-83fd-17e44013d730.png)

**Comment by ekigamba** [comment]
2 days

**Comment by hmakandi** [comment]
@ekigamba The Vitamin schedules do not show in the correct chronological order. They should follow each other every 6 months until the child is 5 years as per the schedule in the [data dictionary](https://docs.google.com/spreadsheets/d/13BL6SCrallzsuTFTUSBlYNomMSUqCEG5JLQo4A8_RR8/edit#gid=1111650937) and it should only show the next one due like the deworming...
![Screenshot_20190826-191941](https://user-images.githubusercontent.com/18394882/63705994-0ab68100-c837-11e9-96b3-fd284ed7a331.jpg)

**Comment by hmakandi** [comment]
The issue is resolved.
