### ISSUE TITLE
Child Registration Data: Change form data relevance

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#53]
Steps: Go to add Patient on the child Register

- [x] Change the Mother's ID to allow AlphaNumeric Characters. This has been changed in the data dictionary

- [x] Default Mother's DOB to be be Jan 1st 1960.

- [x] First and Last name to be required,  Middle name is not required

**Comment by ekigamba** [comment]
4 hours

**Comment by hmakandi** [comment]
@bennsimon  Please edit the mother's identification relevance to be Alpha numeric, e.g. MWI5ZBF6BMT
![Screenshot_20190826-184440](https://user-images.githubusercontent.com/18394882/63703486-beb50d80-c831-11e9-9ac4-69d32bae1fd8.jpg)

**Comment by hmakandi** [comment]
Confirmed
