### ISSUE TITLE
Enable AEFI queries 

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-giz-malawi#54]
Enable querying of AEFIs by either:
- Adding an AEFI table to store the data in a relational format that can be queried by reporting library and other libraries

**Comment by ekigamba** [comment]
**This is not going to be implemented now since we do not need in-app reporting of AEFI** This has been pushed till December or whenever this issue will be revisited

**Comment by hmakandi** [comment]
This was implemented to allow counting of AEFI based on collected information.
