### ISSUE TITLE
Child Death Reporting Form

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-client-giz-malawi#81]
Steps:On the child's profile, go to report deceased
- [x] Add the options below as a drop down on cause of death
Sepsis,Malaria, Diarrhoea, Malnutrition, Palmor Pallor, Acute Respiratory Infection, Meningococal Meningitis, Skin Infection,Diabetes,Cancer, Other

- [x] On select other, have the edit text to specify the cause of death
![Screenshot_1567095018](https://user-images.githubusercontent.com/18394882/63957266-bb6b8d00-ca90-11e9-811e-8c441770c010.png)

**Comment by hmakandi** [comment]
@bennsimon  Report death form, the date field does not store the initial selection, it disappears for some reason. The first click does not work, you have to do it twice.

Steps:->Go to child profile, click on report Death, Click on Date of death.

**Comment by bennsimon** [comment]
It was fixed earlier today

**Comment by hmakandi** [comment]
Works!
