### ISSUE TITLE
When BCG Repeated Dose is undone, the app crashes

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-giz-malawi#88]
- Just give BCG on a kid over 6 weeks and when the BCG scar dialog shows up, click on *No Scar*, Click *Create Reminder*
- Give the **BCG Repeated Dose** and later undo it
- Undo the **BCG Dose**
- Go to the register page
- Go back to the child
- Give the **BCG Dose** again and try going to the register page

The app starts crashing at this point

**Comment by hmakandi** [comment]
This issue has been confirmed solved. Awesome!
