### ISSUE TITLE
Clicking on hamburger menu in ANC Register (right-end) performs a back action

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-giz-malawi#98]
This is in the release 0.1.6 which contains the ANC Register

**Comment by ekigamba** [comment]
Fixed in https://github.com/OpenSRP/opensrp-client-giz-malawi/commit/dfec0b2bd804111615f643e070892bea82ddf5a6

**Comment by hmakandi** [comment]
Confirmed as opening the nav pane
